In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn import linear_model

import warnings
warnings.filterwarnings("ignore")

In [8]:
# Create a dictionary 
data = {
    "Area": [2600, 3000, 3200, 3600, 4000],
    "Bedrooms": [3, 4, 3.5 , 3, 4],
    "Age": [20, 15, 18, 30, 8],
    "Price": [550000, 565000, 610000, 595000, 760000]
}

# Create a dataframe 
df = pd.DataFrame(data)

df.to_csv("Imaginary_House_Data.csv")
df

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.5   18  610000
3  3600       3.0   30  595000
4  4000       4.0    8  760000

In [9]:
reg = linear_model.LinearRegression()

In [17]:
reg.fit(df[["Area", "Bedrooms", "Age"]], df.Price)

LinearRegression()

In [18]:
reg.coef_

array([   132.95417101, -82352.95732879,  -8827.50288319])

In [19]:
reg.intercept_

628806.2221978151

In [25]:
reg.predict([[2400, 3, 60]])

array([171187.18765446])

In [26]:
reg.predict([[2400, 3, 10]])

array([612562.33181394])

In [27]:
reg.predict([[2400, 3, 20]])

array([524287.30298204])